{
 "title": "Network",
 "description": "Network Information",
 "tags": [
  "exadata",
  "prometheus",
  "compute",
  "storage",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "prometheus" },
   {
    "name": "fleet",
    "query": {
     "query": "label_values({__name__=~\"CL_CPUT|DS_CPUT\"},fleet)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values({__name__=~\"CL_CPUT|DS_CPUT\",fleet=~\"$fleet\"},pod)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values({__name__=~\"CL_CPUT|DS_CPUT\",fleet=~\"$fleet\",pod=~\"$pod\"},cluster)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values({__name__=~\"CL_CPUT|DS_CPUT\",fleet=~\"$fleet\",pod=~\"$pod\",cluster=~\"$cluster\"},server)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "{__name__=~\"EXW_ROCE_RX_BY_SEC|EXW_ROCE_TX_BY_SEC\",fleet=~\"$fleet\",pod=~\"$pod\",cluster=~\"$cluster\",server=~\"$server\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RDMA Network ${interface}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "interface",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RX Bytes - ($interface)",
     "type": "timeseries",
     "description": "EXAREL: RoCE bytes received",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_ROCE_RX_BY_SEC{server=~\"$server\", objectName=~\"${interface}.*\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      },
      {
       "expr": "N_IB_MB_RCV_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "TX Bytes - ($interface)",
     "type": "timeseries",
     "description": "EXAREL: RoCE bytes transmitted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "EXW_ROCE_TX_BY_SEC{server=~\"$server\",objectName=~\"${interface}.*\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      },
      {
       "expr": "N_IB_MB_TRANS_SEC{server=~\"$server\"}",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pauses and RoCE Congestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pauses ($interface)",
     "type": "timeseries",
     "description": "EXAREL: RoCE Pause Frames or IB Pauses",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "repeat": "interface",
     "targets": [
      {
       "constant": 6.5,
       "expr": "rate(EXW_ROCE_PAUSE{server=~\"$server\",objectName=~\"${interface}.*\"}[1m])",
       "legendFormat": "{{objectName}}-{{server}}"
      }
     ]
    },
    {
     "title": "RoCE Congestion",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(EXW_ROCE_NP_CNP_SENT{server=~\"$server\",objectName!=\".*eth.*\"}[1m])",
       "legendFormat": "np_cnp_sent-{{objectName}}-{{server}}"
      },
      {
       "expr": "rate(EXW_ROCE_NP_ECN_MARKED_ROCE_PACKETS{server=~\"$server\",objectName!=\".*eth.*\"}[1m])",
       "legendFormat": "np_ecn_marked_roce_packets-{{objectName}}-{{server}}"
      },
      {
       "expr": "rate(EXW_ROCE_RP_CNP_HANDLED{server=~\"$server\",objectName!=\".*eth.*\"}[1m])",
       "legendFormat": "rp_cnp_handled-{{objectName}}-{{server}}"
      },
      {
       "expr": "rate(EXW_ROCE_RP_CNP_IGNORED{server=~\"$server\",objectName!=\".*eth.*\"}[1m])",
       "legendFormat": "rp_cnp_ignored-{{objectName}}-{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RDS Errors",
     "type": "timeseries",
     "description": "EXAREL: rds-info counters",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "constant": 6.5,
       "expr": "rate(EXW_RDS_CONG_SEND_BLOCKED{server=~\"$server\"}[1m])",
       "legendFormat": "RDS_CONG_SEND_BLKD-{{server}}"
      },
      {
       "expr": "rate(EXW_RDS_CONG_SEND_ERROR{server=~\"$server\"}[1m])",
       "legendFormat": "RDS_CONG_SEND_ERROR-{{server}}"
      },
      {
       "expr": "rate(EXW_RDS_IB_MR_1M_POOL_DEPLETED{server=~\"$server\"}[1m])",
       "legendFormat": "RDS_IB_MR_1M_POOL_DEPLETED-{{server}}"
      },
      {
       "expr": "rate(EXW_RDS_IB_RDMA_MR_8K_POOL_DEPLETED{server=~\"$server\"}[1m])",
       "legendFormat": "RDS_IB_RDMA_MR_8K_POOL_DEPLETED({{server}})"
      },
      {
       "expr": "rate(EXW_RDS_IB_TX_STALLED{server=~\"$server\"}[1m])",
       "legendFormat": "RDS_IB_TX_STALLED-{{server}}"
      },
      {
       "expr": "rate(EXW_ROCE_RNR_NAK_RETRY_ERR{server=~\"$server\"}[1m])",
       "legendFormat": "RNR_NAK_RETRY_ERR-{{server}}-{{objectName}}"
      },
      {
       "expr": "rate(EXW_ROCE_LOCAL_ACK_TIMEOUT_ERR{server=~\"$server\"}[1m])",
       "legendFormat": "LOCAL_ACK_TIMEOUT_ERR-{{server}}-{{objectName}}"
      },
      {
       "expr": "EXW_RDS_CONN_RESET{server=~\"$server\"}",
       "legendFormat": "EXW_RDS_CONN_RESET-{{server}}"
      }
     ]
    }
   ]
  }
 ]
}